// Site validator: checks material data, material pages, PDFs, translations and paths.
// It also runs the static page generator in memory and fails when a committed
// file is out of date, so every future page is optimized automatically.
// Run: node tests/validate.mjs
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import vm from 'node:vm';
import { buildSite, esc, KATEX_VERSION } from '../tools/build_pages.mjs';

const require = createRequire(import.meta.url);
const Catalog = require('../assets/js/catalog.js');

const ROOT = process.env.SITE_ROOT || join(dirname(fileURLToPath(import.meta.url)), '..');
const errors = [];
const fail = (msg) => errors.push(msg);
const exists = (p) => existsSync(join(ROOT, p));
const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const isText = (v) => typeof v === 'string' && v.trim().length > 0;

const ID_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const YT_RE = /^[A-Za-z0-9_-]{11}$/;
const YT_DURATION_RE = /^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/;
const YT_UPLOADED_RE = /^(\d{4}-\d{2}-\d{2})(?:T\d{2}:\d{2}(?::\d{2})?(?:Z|[+-]\d{2}:?\d{2})?)?$/;

const REQUIRED_FILES = [
  'index.html',
  'en/index.html',
  'clasa.html',
  'cautare.html',
  'en/cautare.html',
  '404.html',
  'en/404.html',
  'robots.txt',
  'sitemap.xml',
  '_headers',
  '.nojekyll',
  'favicon.svg',
  'favicon.ico',
  'apple-touch-icon.png',
  'assets/img/og-image.png',
  'assets/css/style.css',
  'assets/js/i18n.js',
  'assets/js/catalog.js',
  'assets/js/shell.js',
  'assets/js/site.js',
  'assets/js/searchbox.js',
  'assets/js/home.js',
  'assets/js/clasa.js',
  'assets/js/cautare.js',
  'assets/js/material.js',
  'data/materials.json',
];
for (let g = 5; g <= 12; g++) {
  REQUIRED_FILES.push(`clasa-${g}.html`, `en/clasa-${g}.html`);
}

// Marks of one school class (not of the grade). Materials are shared with other classes, so they must not show them.
const CLASS_MARKS = [
  [/\b[IVX]+-a\s+[A-Z]\d\b/, 'a class name like "IX-a R2"'],
  [/\b(?:[5-9]|1[0-2])[A-Z]\d\b/, 'a class code like "9R2"'],
  [/\bS\d{1,2}\s*:\s*\d/, 'a school week like "S2: 14"'],
  [/\b\d{1,2}\.\d{1,2}\.20\d{2}\b/, 'a calendar date like "16.09.2026"'],
];
const ANSWER_HEADINGS = ['raspunsuri si indicatii', 'barem de evaluare', 'indicatii de rezolvare'];

function walk(dir, out = []) {
  for (const name of readdirSync(join(ROOT, dir))) {
    if (name.startsWith('.') || ['node_modules', 'docs', 'tests', 'tools'].includes(name)) continue;
    const rel = dir ? `${dir}/${name}` : name;
    if (statSync(join(ROOT, rel)).isDirectory()) walk(rel, out);
    else out.push(rel);
  }
  return out;
}

function checkClassMarks(where, text) {
  for (const [re, what] of CLASS_MARKS) {
    const hit = text.match(re);
    if (hit) fail(`${where}: contains ${what} ("${hit[0]}"). Remove class-specific details.`);
  }
}

// 1. Required files
for (const f of REQUIRED_FILES) {
  if (!exists(f)) fail(`Missing required file: ${f}`);
}

// 2. Generated files are up to date (the generator owns the page shells)
try {
  const site = buildSite(ROOT);
  for (const [file, content] of site) {
    if (!exists(file)) fail(`${file}: is generated by tools/build_pages.mjs. Run: node tools/build_pages.mjs`);
    else if (read(file) !== content) fail(`${file}: is out of date. Run: node tools/build_pages.mjs`);
  }
} catch (e) {
  fail(`tools/build_pages.mjs failed: ${e.message}`);
}

// 3. Data
let data = null;
if (exists('data/materials.json')) {
  const raw = read('data/materials.json');
  try {
    data = JSON.parse(raw);
    if (!Array.isArray(data.topics)) fail('data/materials.json: "topics" must be an array');
    if (!Array.isArray(data.materials)) fail('data/materials.json: "materials" must be an array');
    checkClassMarks('data/materials.json', raw);
  } catch (e) {
    fail(`data/materials.json is not valid JSON: ${e.message}`);
  }
}
const topics = data && Array.isArray(data.topics) ? data.topics : [];
const materials = data && Array.isArray(data.materials) ? data.materials : [];

const topicIds = new Set();
for (const [i, t] of topics.entries()) {
  const where = `topic #${i} (${t && t.id})`;
  if (!t || typeof t !== 'object') { fail(`${where}: must be an object`); continue; }
  if (!isText(t.id) || !ID_RE.test(t.id)) fail(`${where}: id must be lowercase letters, digits and dashes`);
  if (topicIds.has(t.id)) fail(`${where}: duplicate topic id`);
  topicIds.add(t.id);
  if (!Number.isInteger(t.grade) || t.grade < 5 || t.grade > 12) fail(`${where}: grade must be an integer 5-12`);
  if (!t.title || !isText(t.title.ro)) fail(`${where}: title.ro is required`);
  if (!t.title || !isText(t.title.en)) fail(`${where}: title.en is required`);
}

const materialIds = new Set();
const listedPdfs = new Set();
for (const [i, m] of materials.entries()) {
  const where = `material #${i} (${m && m.id})`;
  if (!m || typeof m !== 'object') { fail(`${where}: must be an object`); continue; }
  if (!isText(m.id) || !ID_RE.test(m.id)) fail(`${where}: id must be lowercase letters, digits and dashes`);
  if (materialIds.has(m.id)) fail(`${where}: duplicate material id`);
  materialIds.add(m.id);
  if (!topicIds.has(m.topic)) fail(`${where}: topic "${m.topic}" does not exist`);
  if (!Catalog.KINDS.includes(m.kind)) fail(`${where}: kind must be one of ${Catalog.KINDS.join(', ')}`);
  if (!m.title || !isText(m.title.ro)) fail(`${where}: title.ro is required`);
  if (!m.title || !isText(m.title.en)) fail(`${where}: title.en is required`);
  if (!Catalog.isValidDate(m.published)) fail(`${where}: published must be a real date YYYY-MM-DD`);
  if (m.updated !== undefined) {
    if (!Catalog.isValidDate(m.updated)) fail(`${where}: updated must be a real date YYYY-MM-DD`);
    else if (m.updated < m.published) fail(`${where}: updated must not be before published`);
  }
  for (const lang of ['ro', 'en']) {
    const d = m.description && m.description[lang];
    if (!isText(d)) fail(`${where}: description.${lang} is required`);
    else if ([...d].length < 70 || [...d].length > 160) {
      fail(`${where}: description.${lang} must be 70-160 characters (is ${[...d].length})`);
    }
  }
  if (m.youtube === null || m.youtube === undefined) {
    if (m.youtube !== null) fail(`${where}: youtube must be null or { "id", "uploaded", "duration" }`);
  } else if (typeof m.youtube !== 'object') {
    fail(`${where}: youtube must be null or { "id", "uploaded", "duration" }`);
  } else {
    if (!(typeof m.youtube.id === 'string' && YT_RE.test(m.youtube.id))) {
      fail(`${where}: youtube.id must be an 11-character YouTube video ID`);
    }
    const up = YT_UPLOADED_RE.exec(String(m.youtube.uploaded || ''));
    if (!up || !Catalog.isValidDate(up[1])) {
      fail(`${where}: youtube.uploaded must be an ISO date or date-time`);
    }
    const dur = YT_DURATION_RE.exec(String(m.youtube.duration || ''));
    if (!dur || dur[0] === 'PT' || (!dur[1] && !dur[2] && !dur[3])) {
      fail(`${where}: youtube.duration must be an ISO 8601 duration like "PT7M31S"`);
    }
  }
  if (m.keywords !== undefined) {
    const ok = m.keywords && typeof m.keywords === 'object'
      && ['ro', 'en'].every((lang) => m.keywords[lang] === undefined || (Array.isArray(m.keywords[lang]) && m.keywords[lang].every(isText)));
    if (!ok) fail(`${where}: keywords must be { "ro": [text], "en": [text] }`);
  }
  // Grade forms in keywords (audit F2): the Arabic form students type.
  // Only checked when the list exists; keywords stay optional per AGENTS.md.
  const gradeOf = topics.find((t) => t.id === m.topic)?.grade;
  if (gradeOf) {
    if (m.keywords && m.keywords.ro !== undefined && !m.keywords.ro.includes(`clasa a ${gradeOf}-a`)) {
      fail(`${where}: keywords.ro must include "clasa a ${gradeOf}-a" (audit F2)`);
    }
    if (m.keywords && m.keywords.en !== undefined && !m.keywords.en.includes(`grade ${gradeOf}`)) {
      fail(`${where}: keywords.en must include "grade ${gradeOf}" (audit F2)`);
    }
  }

  const expectedPdf = `materiale/pdf/${m.id}.pdf`;
  if (m.kind === 'quiz' && m.pdf !== null) {
    fail(`${where}: pdf must be null for a quiz`);
  } else if (m.pdf !== null) {
    if (m.pdf !== expectedPdf) {
      fail(`${where}: pdf must be "${expectedPdf}" or null`);
    } else if (!exists(expectedPdf)) {
      fail(`${where}: missing file ${expectedPdf}`);
    } else {
      listedPdfs.add(expectedPdf);
      if (readFileSync(join(ROOT, expectedPdf)).subarray(0, 5).toString('latin1') !== '%PDF-') fail(`${expectedPdf}: is not a PDF file`);
    }
  }

  const page = `materiale/${m.id}.html`;
  if (!exists(page)) { fail(`${where}: missing file ${page}`); continue; }
  const html = read(page);
  const topic = topics.find((t) => t.id === m.topic);
  if (m.kind === 'quiz') {
    if (!/^<!doctype html>/i.test(html.trimStart())) fail(`${page}: must start with <!doctype html>`);
    if (!html.includes('<html lang="ro"')) fail(`${page}: must have <html lang="ro">`);
    const back = topic ? `href="../clasa-${topic.grade}.html"` : null;
    if (!back || !html.includes(back)) fail(`${page}: must link back to ../clasa-<grade>.html`);
    if (!html.includes('<!-- seo -->') || !html.includes('<!-- /seo -->')) {
      fail(`${page}: must contain the <!-- seo --> block written by tools/build_pages.mjs`);
    }
  } else {
    if (!html.includes(`data-id="${m.id}"`)) fail(`${page}: must contain data-id="${m.id}"`);
    if (!html.includes('data-lang="ro"')) fail(`${page}: must contain an article with data-lang="ro"`);
    if (html.includes('data-lang="en"')) fail(`${page}: the English article lives in en/${page}`);
    if (!html.includes('data-root="../"')) fail(`${page}: body must have data-root="../"`);
    if (!html.includes(`katex@${KATEX_VERSION}/`)) fail(`${page}: must load KaTeX ${KATEX_VERSION}`);
    const enPage = `en/${page}`;
    if (!exists(enPage)) {
      fail(`${where}: missing file ${enPage}`);
    } else {
      const enHtml = read(enPage);
      if (!enHtml.includes('data-lang="en"')) fail(`${enPage}: must contain an article with data-lang="en"`);
      if (enHtml.includes('data-lang="ro"')) fail(`${enPage}: the Romanian article lives in ${page}`);
      if (!enHtml.includes('data-root="../../"')) fail(`${enPage}: body must have data-root="../../"`);
      if (!enHtml.includes(`katex@${KATEX_VERSION}/`)) fail(`${enPage}: must load KaTeX ${KATEX_VERSION}`);
      checkClassMarks(enPage, enHtml);
      const enPlain = Catalog.normalize(enHtml.replace(/<[^>]+>/g, ' ')).replace(/\s+/g, ' ');
      for (const phrase of ANSWER_HEADINGS) {
        if (enPlain.includes(phrase)) fail(`${enPage}: contains "${phrase}". Published materials must not include answers.`);
      }
    }
  }
  checkClassMarks(page, html);
  const plain = Catalog.normalize(html.replace(/<[^>]+>/g, ' ')).replace(/\s+/g, ' ');
  for (const phrase of ANSWER_HEADINGS) {
    if (plain.includes(phrase)) fail(`${page}: contains "${phrase}". Published materials must not include answers.`);
  }
}

// Per-grade intros (audit F3): unique body text naming the year's chapters.
// The grade page shows the intro and uses its first sentence as the meta description.
if (!data) {
  // Invalid JSON is already reported above; nothing more to check here.
} else if (data.grades === undefined) {
  fail('data/materials.json: "grades" with per-grade intro.ro / intro.en is required (audit F3)');
} else if (!data.grades || typeof data.grades !== 'object' || Array.isArray(data.grades)) {
  fail('data/materials.json: "grades" must be an object keyed by grade (5-12)');
} else {
  for (let g = 5; g <= 12; g++) {
    const entry = data.grades[String(g)];
    const where = `grades.${g}`;
    if (!entry || typeof entry !== 'object') { fail(`${where}: intro is required`); continue; }
    for (const lang of ['ro', 'en']) {
      const intro = entry.intro && entry.intro[lang];
      if (!isText(intro)) { fail(`${where}: intro.${lang} is required`); continue; }
      const words = intro.trim().split(/\s+/).length;
      if (words < 60 || words > 100) fail(`${where}: intro.${lang} must be 60-100 words (is ${words})`);
      const first = (intro.trim().match(/^.*?[.!?…](?=\s|$)/s) || [intro.trim()])[0].trim();
      const len = [...first].length;
      if (len < 70 || len > 160) fail(`${where}: intro.${lang} first sentence must be 70-160 characters (is ${len})`);
      checkClassMarks(`${where} intro.${lang}`, intro);
      if (/[şţŞŢ]/.test(intro)) fail(`${where} intro.${lang}: uses cedilla letters (ş ţ). Use comma-below letters (ș ț).`);
    }
  }
  for (const key of Object.keys(data.grades)) {
    if (!/^([5-9]|1[0-2])$/.test(key)) fail(`grades.${key}: unknown grade (must be 5-12)`);
  }
}

// Every file in materiale/ must be listed in the data
if (exists('materiale')) {
  for (const name of readdirSync(join(ROOT, 'materiale'))) {
    if (name === 'pdf') continue;
    if (extname(name) !== '.html') { fail(`materiale/${name}: only material pages (.html) and the pdf folder belong here`); continue; }
    if (!materialIds.has(name.slice(0, -5))) fail(`materiale/${name}: not listed in data/materials.json`);
  }
}
// en/materiale/ holds only listed materials, never the quiz (it is Romanian only)
const kindOf = new Map(materials.map((m) => [m.id, m.kind]));
if (exists('en/materiale')) {
  for (const name of readdirSync(join(ROOT, 'en', 'materiale'))) {
    if (extname(name) !== '.html') { fail(`en/materiale/${name}: only material pages (.html) belong here`); continue; }
    const id = name.slice(0, -5);
    if (!materialIds.has(id)) fail(`en/materiale/${name}: not listed in data/materials.json`);
    else if (kindOf.get(id) === 'quiz') fail(`en/materiale/${name}: the quiz is Romanian only and must not have an English page`);
  }
}
if (exists('materiale/pdf')) {
  for (const name of readdirSync(join(ROOT, 'materiale', 'pdf'))) {
    if (!listedPdfs.has(`materiale/pdf/${name}`)) fail(`materiale/pdf/${name}: not listed in data/materials.json`);
  }
}

// 4. Translations
let dict = null;
if (exists('assets/js/i18n.js')) {
  try {
    const sandbox = { window: {}, localStorage: undefined, document: undefined };
    vm.runInNewContext(read('assets/js/i18n.js'), sandbox);
    dict = sandbox.window.I18N;
    if (!dict || !dict.ro || !dict.en) fail('assets/js/i18n.js must define window.I18N with ro and en');
  } catch (e) {
    fail(`assets/js/i18n.js failed to load: ${e.message}`);
  }
}

const files = walk('');
const codeFiles = files.filter((f) => ['.html', '.js', '.css'].includes(extname(f)));

if (dict && dict.ro && dict.en) {
  const used = new Set();
  for (const f of codeFiles) {
    const src = read(f);
    for (const m of src.matchAll(/data-i18n="([^"]+)"/g)) used.add(m[1]);
    for (const m of src.matchAll(/\bt\(\s*'([^']+)'\s*\)/g)) used.add(m[1]);
  }
  for (const key of used) {
    for (const lang of ['ro', 'en']) {
      if (!isText(dict[lang][key])) fail(`Translation key "${key}" missing in ${lang}`);
    }
  }
  for (const key of Object.keys(dict.ro)) {
    if (!(key in dict.en)) fail(`Translation key "${key}" exists in ro but not in en`);
  }
  for (const key of Object.keys(dict.en)) {
    if (!(key in dict.ro)) fail(`Translation key "${key}" exists in en but not in ro`);
  }
}

// 5. Relative paths only (the site must work under any base path)
for (const f of codeFiles) {
  const src = read(f);
  const bad = src.match(/(?:href|src)\s*=\s*["']\/(?!\/)/g);
  if (bad) fail(`${f}: uses an absolute path (${bad[0]}...). Use relative paths.`);
  if (extname(f) === '.css' && /url\(\s*["']?\/(?!\/)/.test(src)) fail(`${f}: uses an absolute url(/...). Use relative paths.`);
}

// 6. Romanian diacritics use comma-below (ș ț), not the look-alike cedilla letters (ş ţ)
for (const f of [...codeFiles, 'data/materials.json']) {
  if (exists(f) && /[şţŞŢ]/.test(read(f))) fail(`${f}: uses cedilla letters (ş ţ). Use comma-below letters (ș ț).`);
}

// 7. Internal links in static HTML point to files that exist
for (const f of files.filter((x) => extname(x) === '.html')) {
  const src = read(f);
  for (const m of src.matchAll(/(?:href|src)\s*=\s*"([^"]+)"/g)) {
    const url = m[1];
    if (/^(https?:|mailto:|tel:|#|data:)/.test(url) || url.includes('${')) continue;
    const path = url.split(/[?#]/)[0];
    if (path && !existsSync(join(ROOT, dirname(f), path))) fail(`${f}: link to missing file "${url}"`);
  }
}

// 8. SEO head tags and headers (audit Phase 3)
for (const f of files.filter((x) => extname(x) === '.html')) {
  const src = read(f);
  if (!src.includes('<head')) continue;
  if (src.includes('noindex')) {
    if (src.includes('max-image-preview')) fail(`${f}: noindex page must not contain max-image-preview`);
  } else {
    if (!src.includes('max-image-preview:large, max-snippet:-1, max-video-preview:-1')) {
      fail(`${f}: indexable page must contain robots max-image-preview:large, max-snippet:-1, max-video-preview:-1`);
    }
    for (const tag of ['og:image:width', 'og:image:height', 'og:image:alt']) {
      if (!src.includes(tag)) fail(`${f}: indexable page must contain ${tag}`);
    }
  }
}
for (const f of ['index.html', 'en/index.html']) {
  if (exists(f)) {
    const src = read(f);
    if (!src.includes('"EducationalOrganization"')) fail(`${f}: must contain an EducationalOrganization node (audit F5)`);
    if (!src.includes('"logo"')) fail(`${f}: EducationalOrganization must have a logo`);
  }
}
if (exists('_headers')) {
  const h = read('_headers');
  if (!h.includes('/assets/*') || !h.includes('Cache-Control: public, max-age=86400')) {
    fail('_headers: must set "Cache-Control: public, max-age=86400" for /assets/* (audit F4)');
  }
  if (!h.includes('/materiale/pdf/*') || !h.includes('Cache-Control: public, max-age=86400')) {
    fail('_headers: must set "Cache-Control: public, max-age=86400" for /materiale/pdf/* (audit F4)');
  }
  if (!h.includes('https://:version.:project.pages.dev/*')) {
    fail('_headers: must noindex preview deployments with "https://:version.:project.pages.dev/*" (audit F6)');
  }
  if (/^https:\/\/:project\.pages\.dev\/\*$/m.test(h)) {
    fail('_headers: must not noindex "https://:project.pages.dev/*" — that would noindex production');
  }
}
// Grade titles carry both numeral forms (audit F2); descriptions are unique (audit F3).
{
  const seen = new Map();
  for (let g = 5; g <= 12; g++) {
    for (const f of [`clasa-${g}.html`, `en/clasa-${g}.html`]) {
      if (!exists(f)) continue;
      const src = read(f);
      const title = (src.match(/<title>([\s\S]*?)<\/title>/) || [, ''])[1];
      if (f === `clasa-${g}.html`) {
        if (!title.includes(`clasa a ${g}-a`) || !title.includes(`a ${Catalog.ROMAN[g]}-a`)) {
          fail(`${f}: title must contain both "clasa a ${g}-a" and "a ${Catalog.ROMAN[g]}-a" (audit F2)`);
        }
      } else if (!title.includes(`Grade ${g}`)) {
        fail(`${f}: title must contain "Grade ${g}"`);
      }
      const desc = (src.match(/<meta name="description" content="([^"]*)"/) || [, null])[1];
      if (desc && !src.includes('noindex')) {
        if (seen.has(desc)) fail(`${f}: description duplicates ${seen.get(desc)} (audit F3)`);
        else seen.set(desc, f);
      }
      // The full intro stays in the server HTML even though the browser
      // collapses it behind a "more" button (SEO: crawlers see everything).
      if (data && data.grades && data.grades[String(g)] && data.grades[String(g)].intro) {
        const lang = f.startsWith('en/') ? 'en' : 'ro';
        const intro = data.grades[String(g)].intro[lang] || data.grades[String(g)].intro.ro;
        if (intro && !src.includes(esc(intro))) fail(`${f}: must contain the full grade intro in the HTML`);
      }
    }
  }
}

// The brand mark borrows the header ink for its letters, but the highlighter
// under them needs its own colour: the page highlighter is nearly invisible on
// the dark theme, so a shared variable would hide half the logo there.
{
  const css = read('assets/css/style.css');
  const markerDefs = (css.match(/--brand-marker\s*:/g) || []).length;
  if (markerDefs < 2) {
    fail(`assets/css/style.css: --brand-marker must be set for the light and the dark theme (found ${markerDefs})`);
  }
  for (const rule of ['.brand-mark', '.brand-text']) {
    if (!css.includes(`${rule} {`)) fail(`assets/css/style.css: missing a rule for ${rule}`);
  }
}

if (errors.length) {
  console.error(`FAIL: ${errors.length} problem(s)`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}
console.log(`PASS: ${topics.length} topics, ${materials.length} materials, ${codeFiles.length} files checked`);
