// Site validator: checks material data, material pages, PDFs, translations and paths.
// It also runs the static page generator in memory and fails when a committed
// file is out of date, so every future page is optimized automatically.
// Run: node tests/validate.mjs
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import vm from 'node:vm';
import { buildSite, esc, KATEX_VERSION, ADMIN_FOLDER, FONTS, readArticle, countHeadings, parseClipSection, compareClipSections, subheadingCounts } from '../tools/build_pages.mjs';
import { checkItems, checkTrueKeys } from '../tools/results.mjs';

const require = createRequire(import.meta.url);
const Catalog = require('../assets/js/catalog.js');
const Visibility = require('../assets/js/visibility.js');

const ROOT = process.env.SITE_ROOT || join(dirname(fileURLToPath(import.meta.url)), '..');
const errors = [];
const fail = (msg) => errors.push(msg);
const exists = (p) => existsSync(join(ROOT, p));
const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const isText = (v) => typeof v === 'string' && v.trim().length > 0;

const ID_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const UID_RE = /^[1-9][0-9]{3,}$/;
const YT_RE = /^[A-Za-z0-9_-]{11}$/;
const SEO_TITLE_MAX = 50;
const YT_DURATION_RE = /^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/;
const YT_UPLOADED_RE = /^(\d{4}-\d{2}-\d{2})(?:T\d{2}:\d{2}(?::\d{2})?(?:Z|[+-]\d{2}:?\d{2})?)?$/;

const REQUIRED_FILES = [
  'index.html',
  'en/index.html',
  'clasa.html',
  'cautare.html',
  'en/cautare.html',
  '404.html',
  'en/404.html',
  'robots.txt',
  'sitemap.xml',
  'sitemap.xsl',
  '_headers',
  '_redirects',
  '.nojekyll',
  'favicon.svg',
  'favicon.ico',
  'apple-touch-icon.png',
  'assets/img/og-image.png',
  'assets/css/style.css',
  'assets/js/i18n.js',
  'assets/js/catalog.js',
  'assets/js/visibility.js',
  'assets/js/answers.js',
  'assets/js/check.js',
  'assets/js/shell.js',
  'assets/js/site.js',
  'assets/js/searchbox.js',
  'assets/js/home.js',
  'assets/js/clasa.js',
  'assets/js/cautare.js',
  'assets/js/material.js',
  'data/materials.source.json',
  '_routes.json',
  `${ADMIN_FOLDER}/index.html`,
  `${ADMIN_FOLDER}/admin.js`,
  `${ADMIN_FOLDER}/admin.css`,
  `${ADMIN_FOLDER}/rezultate.html`,
  `${ADMIN_FOLDER}/rezultate.js`,
  'functions/tm25mlg/api/_middleware.js',
  'functions/tm25mlg/api/materials.js',
  'functions/tm25mlg/api/save.js',
  '.github/workflows/visibility.yml',
];
for (let g = 5; g <= 12; g++) {
  REQUIRED_FILES.push(`clasa-${g}.html`, `en/clasa-${g}.html`);
}

// Marks of one school class (not of the grade). Materials are shared with other classes, so they must not show them.
const CLASS_MARKS = [
  [/\b[IVX]+-a\s+[A-Z]\d\b/, 'a class name like "IX-a R2"'],
  [/\b(?:[5-9]|1[0-2])[A-Z]\d\b/, 'a class code like "9R2"'],
  [/\bS\d{1,2}\s*:\s*\d/, 'a school week like "S2: 14"'],
  [/\b\d{1,2}\.\d{1,2}\.20\d{2}\b/, 'a calendar date like "16.09.2026"'],
];
const ANSWER_HEADINGS = ['raspunsuri si indicatii', 'barem de evaluare', 'indicatii de rezolvare'];

function walk(dir, out = []) {
  for (const name of readdirSync(join(ROOT, dir))) {
    if (name.startsWith('.') || ['node_modules', 'docs', 'tests', 'tools'].includes(name)) continue;
    const rel = dir ? `${dir}/${name}` : name;
    if (statSync(join(ROOT, rel)).isDirectory()) walk(rel, out);
    else out.push(rel);
  }
  return out;
}

// YouTube ids of the materials. An id cannot be changed, and one such as
// "ab-9R2xyzAB" reads like a class code, so the class-mark scan skips them.
const VIDEO_IDS = new Set();

function checkClassMarks(where, text) {
  for (const id of VIDEO_IDS) text = text.split(id).join('');
  for (const [re, what] of CLASS_MARKS) {
    const hit = text.match(re);
    if (hit) fail(`${where}: contains ${what} ("${hit[0]}"). Remove class-specific details.`);
  }
}

// Answers live only in data/results/ and tm25mlg/raspunsuri/ (and never in
// material pages, PDFs or the materials JSON files). The answer-heading rule
// never runs on those two folders; every other place keeps it.
function checkNoAnswers(where, text) {
  const plain = Catalog.normalize(String(text).replace(/<[^>]+>/g, ' ')).replace(/\s+/g, ' ');
  for (const phrase of ANSWER_HEADINGS) {
    if (plain.includes(phrase)) fail(`${where}: contains "${phrase}". Published materials must not include answers.`);
  }
}

// 1. Required files
for (const f of REQUIRED_FILES) {
  if (!exists(f)) fail(`Missing required file: ${f}`);
}

// 2. Generated files are up to date (the generator owns the page shells)
try {
  const site = buildSite(ROOT);
  for (const [file, content] of site) {
    if (!exists(file)) fail(`${file}: is generated by tools/build_pages.mjs. Run: node tools/build_pages.mjs`);
    else if (read(file) !== content) fail(`${file}: is out of date. Run: node tools/build_pages.mjs`);
  }
} catch (e) {
  fail(`tools/build_pages.mjs failed: ${e.message}`);
}

// 3. Data: the source of truth. The public data/materials.json is generated
// from it (visible materials only) and is checked separately below.
const SOURCE = 'data/materials.source.json';
let data = null;
if (exists(SOURCE)) {
  const raw = read(SOURCE);
  try {
    data = JSON.parse(raw);
    for (const m of Array.isArray(data.materials) ? data.materials : []) {
      for (const v of Array.isArray(m.youtube) ? m.youtube : []) if (v && typeof v.id === 'string') VIDEO_IDS.add(v.id);
    }
    if (!Array.isArray(data.topics)) fail(`${SOURCE}: "topics" must be an array`);
    if (!Array.isArray(data.materials)) fail(`${SOURCE}: "materials" must be an array`);
    checkClassMarks(SOURCE, raw);
    checkNoAnswers(SOURCE, raw);
  } catch (e) {
    fail(`${SOURCE} is not valid JSON: ${e.message}`);
  }
}
const topics = data && Array.isArray(data.topics) ? data.topics : [];
const materials = data && Array.isArray(data.materials) ? data.materials : [];

const topicIds = new Set();
for (const [i, t] of topics.entries()) {
  const where = `topic #${i} (${t && t.id})`;
  if (!t || typeof t !== 'object') { fail(`${where}: must be an object`); continue; }
  if (!isText(t.id) || !ID_RE.test(t.id)) fail(`${where}: id must be lowercase letters, digits and dashes`);
  if (topicIds.has(t.id)) fail(`${where}: duplicate topic id`);
  topicIds.add(t.id);
  if (!Number.isInteger(t.grade) || t.grade < 5 || t.grade > 12) fail(`${where}: grade must be an integer 5-12`);
  if (!t.title || !isText(t.title.ro)) fail(`${where}: title.ro is required`);
  if (!t.title || !isText(t.title.en)) fail(`${where}: title.en is required`);
}

// A clip's section is the n-th <h2> of the article, or "N.M" for the m-th
// <h3> inside the n-th <h2>. An empty article shows every card above it, so
// it needs no headings.
function checkClipSections(where, m, page, html, lang) {
  if (!Array.isArray(m.youtube) || m.youtube.length < 2) return;
  const article = readArticle(html, lang) || '';
  if (!Catalog.hasArticleContent(article)) return;
  const count = countHeadings(article);
  const subs = subheadingCounts(article);
  m.youtube.forEach((v, i) => {
    if (!v || v.section === undefined) return;
    const parsed = parseClipSection(v.section);
    if (!parsed) return;
    if (parsed.h2 > count) {
      fail(`${page}: youtube[${i}].section ${v.section} but the article has ${count} <h2>`);
    } else if (parsed.h3 > 0 && parsed.h3 > (subs[parsed.h2 - 1] || 0)) {
      fail(`${page}: youtube[${i}].section ${v.section} but section ${parsed.h2} has ${subs[parsed.h2 - 1] || 0} <h3>`);
    }
  });
}

// A generated clip slot is the one thing the generator inserts inside the
// article; readArticle strips it back out. If it survives, either a hand
// edit re-shaped it past what stripClipSlots recognises, or the page was
// never regenerated after a data change.
function checkNoLeftoverSlot(page, html, lang) {
  const article = readArticle(html, lang) || '';
  if (article.includes('data-generated="clips"')) {
    fail(`${page}: a generated clip slot is left inside the article; run node tools/build_pages.mjs`);
  }
}

const materialUids = new Set();
const materialNames = new Set();
const listedPdfs = new Set();
const superseding = [];
for (const [i, m] of materials.entries()) {
  const where = `material #${i}`;
  if (!m || typeof m !== 'object') { fail(`${where}: must be an object`); continue; }
  if (!isText(m.uid) || !UID_RE.test(m.uid)) {
    fail(`${where}: uid must be 4 or more digits, not starting with 0`);
  } else if (materialUids.has(m.uid)) {
    fail(`${where}: duplicate uid "${m.uid}"`);
  } else {
    materialUids.add(m.uid);
  }
  if (!isText(m.slug) || !ID_RE.test(m.slug)) {
    fail(`${where}: slug must be lowercase letters, digits and dashes`);
  }
  const name = `${m.slug || '?'}-${m.uid || '?'}`;
  if (materialNames.has(name)) fail(`${where}: duplicate material name "${name}"`);
  materialNames.add(name);
  if (!topicIds.has(m.topic)) fail(`${where}: topic "${m.topic}" does not exist`);
  if (!Catalog.KINDS.includes(m.kind)) fail(`${where}: kind must be one of ${Catalog.KINDS.join(', ')}`);
  if (!m.title || !isText(m.title.ro)) fail(`${where}: title.ro is required`);
  if (!m.title || !isText(m.title.en)) fail(`${where}: title.en is required`);
  if (!Catalog.isValidDate(m.published)) fail(`${where}: published must be a real date YYYY-MM-DD`);
  if (m.updated !== undefined) {
    if (!Catalog.isValidDate(m.updated)) fail(`${where}: updated must be a real date YYYY-MM-DD`);
    else if (m.updated < m.published) fail(`${where}: updated must not be before published`);
  }
  for (const lang of ['ro', 'en']) {
    const d = m.description && m.description[lang];
    if (!isText(d)) fail(`${where}: description.${lang} is required`);
    else if ([...d].length < 70 || [...d].length > 160) {
      fail(`${where}: description.${lang} must be 70-160 characters (is ${[...d].length})`);
    }
  }
  // seoTitle: the short <title> for search results. The page adds the grade
  // (about 19 characters), so the field itself stays short.
  if (m.seoTitle !== undefined) {
    if (!m.seoTitle || typeof m.seoTitle !== 'object' || Array.isArray(m.seoTitle)) {
      fail(`${where}: seoTitle must be { "ro": text, "en": text }`);
    } else {
      for (const key of Object.keys(m.seoTitle)) if (!['ro', 'en'].includes(key)) fail(`${where}: seoTitle: unknown field "${key}"`);
      for (const lang of ['ro', 'en']) {
        const t = m.seoTitle[lang];
        if (!isText(t)) fail(`${where}: seoTitle.${lang} is required when seoTitle is present`);
        else if ([...t].length > SEO_TITLE_MAX) fail(`${where}: seoTitle.${lang} must be at most ${SEO_TITLE_MAX} characters (is ${[...t].length})`);
      }
    }
  }
  const VIDEO_KEYS = ['id', 'uploaded', 'duration', 'title', 'section', 'description'];
  if (m.youtube !== null) {
    if (!Array.isArray(m.youtube) || m.youtube.length === 0) {
      fail(`${where}: youtube must be null or a non-empty list of clips`);
    } else {
      m.youtube.forEach((v, i) => {
        const at = `${where}: youtube[${i}]`;
        if (!v || typeof v !== 'object' || Array.isArray(v)) { fail(`${at} must be an object`); return; }
        for (const key of Object.keys(v)) if (!VIDEO_KEYS.includes(key)) fail(`${at}: unknown field "${key}"`);
        if (!(typeof v.id === 'string' && YT_RE.test(v.id))) fail(`${at}.id must be an 11-character YouTube video ID`);
        const up = YT_UPLOADED_RE.exec(String(v.uploaded || ''));
        if (!up || !Catalog.isValidDate(up[1])) fail(`${at}.uploaded must be an ISO date or date-time`);
        const dur = YT_DURATION_RE.exec(String(v.duration || ''));
        if (!dur || dur[0] === 'PT' || (!dur[1] && !dur[2] && !dur[3])) fail(`${at}.duration must be an ISO 8601 duration like "PT7M31S"`);
        if (!v.title || !isText(v.title.ro) || !isText(v.title.en)) fail(`${at}.title needs ro and en`);
        if (v.section !== undefined && !parseClipSection(v.section)) fail(`${at}.section must be a whole number from 1 or "N.M" like "4.1"`);
        if (v.description !== undefined) {
          for (const lang of ['ro', 'en']) {
            const d = v.description && v.description[lang];
            if (!isText(d)) fail(`${at}.description.${lang} is required when description is present`);
            else if ([...d].length < 70 || [...d].length > 160) fail(`${at}.description.${lang} must be 70-160 characters (is ${[...d].length})`);
          }
        }
      });
      const seen = new Set();
      let lastSection = null;
      m.youtube.forEach((v, i) => {
        if (!v || typeof v !== 'object') return;
        if (seen.has(v.id)) fail(`${where}: youtube: clip "${v.id}" appears twice`);
        seen.add(v.id);
        if (v.section !== undefined && parseClipSection(v.section)) {
          if (lastSection !== null && compareClipSections(v.section, lastSection) < 0) fail(`${where}: youtube[${i}].section must not be lower than the clip before it`);
          lastSection = v.section;
        }
      });
    }
  }
  if (m.kind === 'quiz' && m.youtube !== null) fail(`${where}: youtube must be null for a quiz`);
  if (m.keywords !== undefined) {
    const ok = m.keywords && typeof m.keywords === 'object'
      && ['ro', 'en'].every((lang) => m.keywords[lang] === undefined || (Array.isArray(m.keywords[lang]) && m.keywords[lang].every(isText)));
    if (!ok) fail(`${where}: keywords must be { "ro": [text], "en": [text] }`);
  }
  // Grade forms in keywords (audit F2): the Arabic form students type.
  // Only checked when the list exists; keywords stay optional per AGENTS.md.
  const gradeOf = topics.find((t) => t.id === m.topic)?.grade;
  if (gradeOf) {
    if (m.keywords && m.keywords.ro !== undefined && !m.keywords.ro.includes(`clasa a ${gradeOf}-a`)) {
      fail(`${where}: keywords.ro must include "clasa a ${gradeOf}-a" (audit F2)`);
    }
    if (m.keywords && m.keywords.en !== undefined && !m.keywords.en.includes(`grade ${gradeOf}`)) {
      fail(`${where}: keywords.en must include "grade ${gradeOf}" (audit F2)`);
    }
  }
  // A superseded copy is the newer half of a re-import pair: it stays visible
  // on the site but is noindex until the old copy is deleted.
  if (m.supersedes !== undefined && !UID_RE.test(String(m.supersedes || ''))) {
    fail(`${where}: supersedes must be a uid like "1005"`);
  } else if (m.supersedes !== undefined) {
    superseding.push(m);
  }
  // Visibility: exactly one of three states. Default is visible, so old
  // entries carry neither field. hidden is only ever true, visibleFrom is an
  // ISO date-time with minutes and the Europe/Bucharest offset, and the two
  // never appear together.
  if (m.hidden !== undefined && m.hidden !== true) {
    fail(`${where}: hidden must be true when present (default is visible)`);
  }
  if (m.visibleFrom !== undefined && !Visibility.isValidVisibleFrom(m.visibleFrom)) {
    fail(`${where}: visibleFrom must be "YYYY-MM-DDTHH:MM:00±HH:MM" with the Europe/Bucharest offset (was "${m.visibleFrom}")`);
  }
  if (m.hidden !== undefined && m.visibleFrom !== undefined) {
    fail(`${where}: hidden and visibleFrom never appear together`);
  }
  if (m.aliases !== undefined) {
    const ok = Array.isArray(m.aliases)
      && m.aliases.every((a) => isText(a) && ID_RE.test(a));
    if (!ok) fail(`${where}: aliases must be a list of path names (lowercase letters, digits and dashes)`);
  }
  // Provenance of the PDF: "source" (a file the teacher gave) or "generated"
  // (made from the DOCX). Older entries have no key.
  if (m.import !== undefined && (typeof m.import !== 'object' || m.import === null || Array.isArray(m.import))) {
    fail(`${where}: import must be an object like { "date", "workflow" }`);
  } else if (m.import && m.import.pdf !== undefined && m.import.pdf !== 'source' && m.import.pdf !== 'generated') {
    fail(`${where}: import.pdf must be "source" or "generated"`);
  }

  const expectedPdf = `materiale/pdf/${name}.pdf`;
  if (m.kind === 'quiz' && m.pdf !== null) {
    fail(`${where}: pdf must be null for a quiz`);
  } else if (m.pdf !== null) {
    if (m.pdf !== expectedPdf) {
      fail(`${where}: pdf must be "${expectedPdf}" or null`);
    } else if (!exists(expectedPdf)) {
      fail(`${where}: missing file ${expectedPdf}`);
    } else {
      listedPdfs.add(expectedPdf);
      if (readFileSync(join(ROOT, expectedPdf)).subarray(0, 5).toString('latin1') !== '%PDF-') fail(`${expectedPdf}: is not a PDF file`);
    }
  }

  const page = `materiale/${name}.html`;
  if (!exists(page)) { fail(`${where}: missing file ${page}`); continue; }
  const html = read(page);
  const topic = topics.find((t) => t.id === m.topic);
  if (m.kind === 'quiz') {
    if (!/^<!doctype html>/i.test(html.trimStart())) fail(`${page}: must start with <!doctype html>`);
    if (!html.includes('<html lang="ro"')) fail(`${page}: must have <html lang="ro">`);
    const back = topic ? `href="../clasa-${topic.grade}.html"` : null;
    if (!back || !html.includes(back)) fail(`${page}: must link back to ../clasa-<grade>.html`);
    if (!html.includes('<!-- seo -->') || !html.includes('<!-- /seo -->')) {
      fail(`${page}: must contain the <!-- seo --> block written by tools/build_pages.mjs`);
    }
  } else {
    if (!html.includes(`data-id="${m.uid}"`)) fail(`${page}: must contain data-id="${m.uid}"`);
    if (!html.includes('data-lang="ro"')) fail(`${page}: must contain an article with data-lang="ro"`);
    if (html.includes('data-lang="en"')) fail(`${page}: the English article lives in en/${page}`);
    if (!html.includes('data-root="../"')) fail(`${page}: body must have data-root="../"`);
    if (!html.includes(`katex@${KATEX_VERSION}/`)) fail(`${page}: must load KaTeX ${KATEX_VERSION}`);
    checkClipSections(where, m, page, html, 'ro');
    checkNoLeftoverSlot(page, html, 'ro');
    const enPage = `en/${page}`;
    if (!exists(enPage)) {
      fail(`${where}: missing file ${enPage}`);
    } else {
      const enHtml = read(enPage);
      checkClipSections(where, m, enPage, enHtml, 'en');
      checkNoLeftoverSlot(enPage, enHtml, 'en');
      if (!enHtml.includes('data-lang="en"')) fail(`${enPage}: must contain an article with data-lang="en"`);
      if (enHtml.includes('data-lang="ro"')) fail(`${enPage}: the Romanian article lives in ${page}`);
      if (!enHtml.includes('data-root="../../"')) fail(`${enPage}: body must have data-root="../../"`);
      if (!enHtml.includes(`katex@${KATEX_VERSION}/`)) fail(`${enPage}: must load KaTeX ${KATEX_VERSION}`);
      checkClassMarks(enPage, enHtml);
      checkNoAnswers(enPage, enHtml);
    }
  }
  checkClassMarks(page, html);
  checkNoAnswers(page, html);
}

// Every file must be named exactly <slug>-<uid> for a material in the data.
// byName also powers the alias checks below.
const byName = new Map();
for (const m of materials) {
  if (isText(m.uid) && UID_RE.test(m.uid) && isText(m.slug) && ID_RE.test(m.slug)) {
    byName.set(`${m.slug}-${m.uid}`, m);
  }
}

// Retired materials: a retired uid is never reused, and nextUid is a counter,
// not "highest uid + 1", so a dropped row can never hand out a uid twice.
const retired = data ? (data.retired === undefined ? [] : data.retired) : [];
if (data && !Array.isArray(retired)) {
  fail('data/materials.source.json: "retired" must be an array');
}
const retiredUids = new Set();
if (Array.isArray(retired)) {
  for (const [i, r] of retired.entries()) {
    const where = `retired #${i}`;
    if (!r || typeof r !== 'object') { fail(`${where}: must be an object`); continue; }
    if (!isText(r.uid) || !UID_RE.test(r.uid)) fail(`${where}: uid must be 4 or more digits, not starting with 0`);
    else if (retiredUids.has(r.uid)) fail(`${where}: duplicate retired uid "${r.uid}"`);
    retiredUids.add(r.uid);
    if (!isText(r.slug) || !ID_RE.test(r.slug)) fail(`${where}: slug must be lowercase letters, digits and dashes`);
    if (!Catalog.isValidDate(r.removed)) fail(`${where}: removed must be a real date YYYY-MM-DD`);
    if (r.replacedBy !== null && r.replacedBy !== undefined && !UID_RE.test(String(r.replacedBy || ''))) {
      fail(`${where}: replacedBy must be a uid or null`);
    }
  }
  for (const uid of retiredUids) {
    if (materialUids.has(uid)) fail(`data/materials.source.json: uid "${uid}" appears both in materials and in retired`);
  }
}

// The counter only ever goes up and must stay ahead of every uid that exists.
const nextUid = data ? data.nextUid : undefined;
if (data && !Number.isInteger(nextUid)) {
  fail('data/materials.source.json: "nextUid" counter must be a number');
} else if (data) {
  const taken = [...materialUids, ...retiredUids].map(Number);
  if (taken.some((n) => nextUid <= n)) {
    fail(`data/materials.source.json: nextUid (${nextUid}) must be larger than every uid in materials and retired (max ${Math.max(...taken)})`);
  }
}

// supersedes names a real uid, and both pages of the newer copy stay noindex.
for (const m of superseding) {
  const name = `${m.slug}-${m.uid}`;
  if (!materialUids.has(m.supersedes) && !retiredUids.has(m.supersedes)) {
    fail(`material ${name}: supersedes "${m.supersedes}" does not name a live or retired uid`);
  }
  for (const page of m.kind === 'quiz' ? [`materiale/${name}.html`] : [`materiale/${name}.html`, `en/materiale/${name}.html`]) {
    if (!exists(page)) continue;
    const html = read(page);
    if (!html.includes('noindex, follow')) fail(`${page}: superseded material must be noindex`);
    if (html.includes('max-image-preview')) fail(`${page}: a noindex page must not contain max-image-preview`);
  }
}

// A not-visible material (hidden or scheduled) keeps its page, because the
// article lives in that file, but the page stays noindex until it is revealed.
for (const m of materials) {
  if (Visibility.isVisible(m)) continue;
  const name = `${m.slug}-${m.uid}`;
  for (const page of m.kind === 'quiz' ? [`materiale/${name}.html`] : [`materiale/${name}.html`, `en/materiale/${name}.html`]) {
    if (!exists(page)) continue;
    const html = read(page);
    if (!html.includes('noindex, follow')) fail(`${page}: not-visible material must be noindex`);
    if (html.includes('max-image-preview')) fail(`${page}: a noindex page must not contain max-image-preview`);
  }
}

// The public copy the browser fetches: visible materials only, no nextUid,
// no retired. The --check staleness rule above already pins it byte for byte
// to the generator output; these rules name the failure when it drifts.
if (exists('data/materials.json')) {
  const raw = read('data/materials.json');
  try {
    const pub = JSON.parse(raw);
    if (!Array.isArray(pub.materials)) {
      fail('data/materials.json: "materials" must be an array');
    } else {
      const visibleUids = new Set(materials.filter((m) => Visibility.isVisible(m)).map((m) => m.uid));
      for (const m of pub.materials) {
        if (!visibleUids.has(m.uid)) fail(`data/materials.json: material ${m.uid} is not visible and must not reach the browser`);
      }
      for (const m of materials) {
        if (Visibility.isVisible(m) && !pub.materials.some((x) => x.uid === m.uid)) {
          fail(`data/materials.json: visible material ${m.uid} is missing`);
        }
      }
    }
    if (pub.nextUid !== undefined) fail('data/materials.json: must not contain nextUid (it is generated from the source)');
    if (pub.retired !== undefined) fail('data/materials.json: must not contain retired (it is generated from the source)');
    checkClassMarks('data/materials.json', raw);
    checkNoAnswers('data/materials.json', raw);
  } catch (e) {
    fail(`data/materials.json is not valid JSON: ${e.message}`);
  }
}

// _routes.json sends only the admin API to Functions. Public pages never run
// a Function, so the request quota never touches the public site.
if (exists('_routes.json')) {
  try {
    const routes = JSON.parse(read('_routes.json'));
    const include = routes && routes.include;
    const only = Array.isArray(include) && include.length === 1 && include[0] === `/${ADMIN_FOLDER}/api/*`;
    if (!only) fail(`_routes.json: include must be exactly ["/${ADMIN_FOLDER}/api/*"]`);
    if (routes.exclude !== undefined && !(Array.isArray(routes.exclude) && routes.exclude.length === 0)) {
      fail('_routes.json: exclude must be empty');
    }
  } catch (e) {
    fail(`_routes.json is not valid JSON: ${e.message}`);
  }
}

// Every not-visible material 302s to its grade page; the source data (which
// holds hidden titles) 302s to the home page.
if (exists('_redirects')) {
  const redirects = read('_redirects');
  const gradeOf = new Map(topics.map((t) => [t.id, t.grade]));
  for (const m of materials) {
    if (Visibility.isVisible(m)) continue;
    const name = `${m.slug}-${m.uid}`;
    const grade = gradeOf.get(m.topic);
    const lines = [`/materiale/${name} /clasa-${grade} 302`, `/materiale/${name}.html /clasa-${grade} 302`];
    if (m.kind !== 'quiz') {
      lines.push(`/en/materiale/${name} /en/clasa-${grade} 302`, `/en/materiale/${name}.html /en/clasa-${grade} 302`);
    }
    if (m.pdf) lines.push(`/materiale/pdf/${name}.pdf /clasa-${grade} 302`);
    for (const line of lines) {
      if (!redirects.includes(line)) fail(`_redirects: missing "${line}" for not-visible material ${name}`);
    }
  }
  if (!redirects.includes('/data/materials.source.json / 302')) {
    fail('_redirects: missing "/data/materials.source.json / 302"');
  }
}

// The admin pages are written by hand, not by the generator, so their heads
// could drift from the site: they must carry the same theme script and fonts.
for (const f of [`${ADMIN_FOLDER}/index.html`, `${ADMIN_FOLDER}/rezultate.html`]) {
  if (!exists(f)) continue;
  const html = read(f);
  const head = html.slice(0, html.indexOf('</head>'));
  if (!head.includes("document.documentElement.classList.add('js')")) {
    fail(`${f}: the head must add the "js" class like the generated pages, or the theme button stays hidden`);
  }
  const theme = head.indexOf('matematica.theme');
  if (theme < 0 || theme > head.indexOf('style.css')) {
    fail(`${f}: the head must read the saved theme before the stylesheet`);
  }
  if (!head.includes(`<link rel="stylesheet" href="${FONTS}">`)) {
    fail(`${f}: the head must load the site fonts (FONTS in tools/build_pages.mjs)`);
  }
}

// Pages and the data files contain no answers and no class marks. The admin
// pages are covered too: the list shows every material with its state, and
// the results page shows every result. Their own text never uses the answer
// headings; the key fragment they load is fine.
for (const f of [`${ADMIN_FOLDER}/index.html`, `${ADMIN_FOLDER}/admin.js`, `${ADMIN_FOLDER}/admin.css`,
  `${ADMIN_FOLDER}/rezultate.html`, `${ADMIN_FOLDER}/rezultate.js`]) {
  if (!exists(f)) continue;
  const src = read(f);
  checkClassMarks(f, src);
  checkNoAnswers(f, src);
}

// An alias is an old name of the same material: it must not equal a live name,
// and two materials must never claim the same alias.
const aliasOwner = new Map();
for (const m of materials) {
  const name = `${m.slug}-${m.uid}`;
  if (!byName.has(name)) continue;
  for (const alias of m.aliases || []) {
    if (byName.has(alias)) fail(`material ${name}: alias "${alias}" equals a live material name`);
    if (aliasOwner.has(alias)) fail(`alias "${alias}" is claimed by both ${aliasOwner.get(alias)} and ${name}`);
    aliasOwner.set(alias, name);
  }
}

// Per-grade intros (audit F3): unique body text naming the year's chapters.
// The grade page shows the intro and uses its first sentence as the meta description.
if (!data) {
  // Invalid JSON is already reported above; nothing more to check here.
} else if (data.grades === undefined) {
  fail('data/materials.source.json: "grades" with per-grade intro.ro / intro.en is required (audit F3)');
} else if (!data.grades || typeof data.grades !== 'object' || Array.isArray(data.grades)) {
  fail('data/materials.source.json: "grades" must be an object keyed by grade (5-12)');
} else {
  for (let g = 5; g <= 12; g++) {
    const entry = data.grades[String(g)];
    const where = `grades.${g}`;
    if (!entry || typeof entry !== 'object') { fail(`${where}: intro is required`); continue; }
    for (const lang of ['ro', 'en']) {
      const intro = entry.intro && entry.intro[lang];
      if (!isText(intro)) { fail(`${where}: intro.${lang} is required`); continue; }
      const words = intro.trim().split(/\s+/).length;
      if (words < 60 || words > 100) fail(`${where}: intro.${lang} must be 60-100 words (is ${words})`);
      const first = (intro.trim().match(/^.*?[.!?…](?=\s|$)/s) || [intro.trim()])[0].trim();
      const len = [...first].length;
      if (len < 70 || len > 160) fail(`${where}: intro.${lang} first sentence must be 70-160 characters (is ${len})`);
      checkClassMarks(`${where} intro.${lang}`, intro);
      if (/[şţŞŢ]/.test(intro)) fail(`${where} intro.${lang}: uses cedilla letters (ş ţ). Use comma-below letters (ș ț).`);
    }
  }
  for (const key of Object.keys(data.grades)) {
    if (!/^([5-9]|1[0-2])$/.test(key)) fail(`grades.${key}: unknown grade (must be 5-12)`);
  }
}

// Every file in materiale/, en/materiale/ and materiale/pdf/ is named exactly
// <slug>-<uid> for a material in the data.
if (exists('materiale')) {
  for (const name of readdirSync(join(ROOT, 'materiale'))) {
    if (name === 'pdf') continue;
    if (extname(name) !== '.html') { fail(`materiale/${name}: only material pages (.html) and the pdf folder belong here`); continue; }
    const base = name.slice(0, -5);
    if (!Catalog.parseName(base) || !byName.has(base)) fail(`materiale/${name}: not a <slug>-<uid> name listed in data/materials.source.json`);
  }
}
// en/materiale/ holds only listed materials, never the quiz (it is Romanian only)
if (exists('en/materiale')) {
  for (const name of readdirSync(join(ROOT, 'en', 'materiale'))) {
    if (extname(name) !== '.html') { fail(`en/materiale/${name}: only material pages (.html) belong here`); continue; }
    const base = name.slice(0, -5);
    const material = Catalog.parseName(base) && byName.get(base);
    if (!material) fail(`en/materiale/${name}: not a <slug>-<uid> name listed in data/materials.source.json`);
    else if (material.kind === 'quiz') fail(`en/materiale/${name}: the quiz is Romanian only and must not have an English page`);
  }
}
if (exists('materiale/pdf')) {
  for (const name of readdirSync(join(ROOT, 'materiale', 'pdf'))) {
    const key = `materiale/pdf/${name}`;
    if (!listedPdfs.has(key)) fail(`${key}: not listed in data/materials.source.json`);
    else if (!Catalog.parseName(name.slice(0, -4))) fail(`${key}: file name must be <slug>-<uid>.pdf`);
  }
}

// 4. Translations
let dict = null;
if (exists('assets/js/i18n.js')) {
  try {
    const sandbox = { window: {}, localStorage: undefined, document: undefined };
    vm.runInNewContext(read('assets/js/i18n.js'), sandbox);
    dict = sandbox.window.I18N;
    if (!dict || !dict.ro || !dict.en) fail('assets/js/i18n.js must define window.I18N with ro and en');
  } catch (e) {
    fail(`assets/js/i18n.js failed to load: ${e.message}`);
  }
}

const files = walk('');
const codeFiles = files.filter((f) => ['.html', '.js', '.css'].includes(extname(f)));

// Every shared script and stylesheet a page loads carries a ?v=<content hash>:
// /assets/* is cached for a day, so a new file must never pair with a stale
// cached copy of another one. Only relative page links are hashed; absolute
// URLs (og:image, the JSON-LD logo) stay exempt.
for (const f of files.filter((x) => x.endsWith('.html'))) {
  const html = read(f);
  for (const m of html.matchAll(/(?:src|href)="((?:\.\.\/)*assets\/(?:js|css)\/[^"]*)"/g)) {
    if (!m[1].includes('?v=')) fail(`${f}: ${m[0]} must carry a ?v= content hash`);
  }
}

// A shared script must never be injected at runtime (document.createElement):
// the generator cannot hash a URL built inside a script, so the injected file
// would load without ?v= and could pair with a stale cached copy. Load every
// shared file as a defer page script instead.
if (exists('assets/js')) {
  for (const name of readdirSync(join(ROOT, 'assets', 'js'))) {
    if (!name.endsWith('.js')) continue;
    if (/createElement\(\s*['"]script['"]\s*\)/.test(read(`assets/js/${name}`))) {
      fail(`assets/js/${name}: must not inject a <script> at runtime. Load the shared file as a defer page script instead, so tools/build_pages.mjs gives it a ?v= content hash.`);
    }
  }
}

// Answer keys live in data/results/ and tm25mlg/raspunsuri/ by design: the
// answer-heading rule never runs there, but the class-mark rules do.
for (const f of files.filter((x) => x.startsWith('data/results/') || x.startsWith(`${ADMIN_FOLDER}/raspunsuri/`))) {
  checkClassMarks(f, read(f));
}

// Results: a material has "results" exactly when both of its files exist
// (data/results/<name>.json and tm25mlg/raspunsuri/<name>.html); no file in
// the two folders without a material. A quiz never has results.
const resultsDataEx = (html) => {
  const keys = [];
  for (const m of String(html).matchAll(/\bdata-ex="([^"]+)"/g)) keys.push(m[1]);
  return keys;
};
const resultsSeen = new Set();
for (const m of materials) {
  if (!m || typeof m !== 'object' || !isText(m.uid) || !isText(m.slug)) continue;
  const name = `${m.slug}-${m.uid}`;
  const resultsFile = `data/results/${name}.json`;
  const keyFile = `${ADMIN_FOLDER}/raspunsuri/${name}.html`;
  const hasField = m.results !== undefined;
  const hasFiles = exists(resultsFile) && exists(keyFile);
  if (m.kind === 'quiz' && (hasField || exists(resultsFile) || exists(keyFile))) {
    fail(`material ${name}: a quiz never has results`);
    continue;
  }
  if (hasField && !hasFiles) {
    fail(`material ${name}: "results" needs both ${resultsFile} and ${keyFile}`);
    continue;
  }
  if (!hasField && (exists(resultsFile) || exists(keyFile))) {
    fail(`material ${name}: ${exists(resultsFile) ? resultsFile : keyFile} has no "results" field in data/materials.source.json`);
    continue;
  }
  // A page with data-ex must have results: the button needs a result to check.
  if (!hasField) {
    for (const page of m.kind === 'quiz' ? [] : [`materiale/${name}.html`, `en/materiale/${name}.html`]) {
      if (!exists(page)) continue;
      const keys = resultsDataEx(read(page));
      if (keys.length) fail(`${page}: data-ex has no result for ${keys.join(', ')} (material ${name} has no "results")`);
    }
    continue;
  }
  resultsSeen.add(resultsFile);
  resultsSeen.add(keyFile);
  const where = `material ${name} results`;
  if (typeof m.results !== 'object' || m.results === null
    || !Number.isInteger(m.results.version) || m.results.version < 1
    || !Number.isInteger(m.results.checks) || m.results.checks < 0) {
    fail(`${where}: "results" must be { "version": 1 or more, "checks": 0 or more }`);
    continue;
  }
  let saved = null;
  try {
    saved = JSON.parse(read(resultsFile));
  } catch (e) {
    fail(`${resultsFile} is not valid JSON: ${e.message}`);
    continue;
  }
  if (saved.uid !== m.uid) fail(`${resultsFile}: uid "${saved.uid}" does not match material ${m.uid}`);
  if (saved.version !== m.results.version) fail(`${resultsFile}: version ${saved.version} does not match "results" in data/materials.source.json`);
  for (const problem of checkItems(saved.items)) fail(`${resultsFile}: ${problem}`);
  const checks = checkTrueKeys(saved.items);
  if (checks.length !== m.results.checks) {
    fail(`${where}: checks is ${m.results.checks} but the file holds ${checks.length} check:true items`);
  }
  // The data-ex set of both pages equals the check:true keys; unique per page.
  for (const page of m.kind === 'quiz' ? [] : [`materiale/${name}.html`, `en/materiale/${name}.html`]) {
    if (!exists(page)) continue;
    const keys = resultsDataEx(read(page));
    if (new Set(keys).size !== keys.length) fail(`${page}: a data-ex value must be unique on its page`);
    const missing = checks.filter((k) => !keys.includes(k));
    const extra = keys.filter((k) => !checks.includes(k));
    if (missing.length) fail(`${page}: data-ex is missing ${missing.join(', ')}`);
    if (extra.length) fail(`${page}: data-ex has no result for ${extra.join(', ')}`);
  }
}
for (const f of files.filter((x) => x.startsWith('data/results/') || x.startsWith(`${ADMIN_FOLDER}/raspunsuri/`))) {
  if (!resultsSeen.has(f)) fail(`${f}: not a <slug>-<uid> name with "results" in data/materials.source.json`);
}

if (dict && dict.ro && dict.en) {
  const used = new Set();
  for (const f of codeFiles) {
    const src = read(f);
    for (const m of src.matchAll(/data-i18n="([^"]+)"/g)) used.add(m[1]);
    for (const m of src.matchAll(/\bt\(\s*'([^']+)'\s*\)/g)) used.add(m[1]);
  }
  for (const key of used) {
    for (const lang of ['ro', 'en']) {
      if (!isText(dict[lang][key])) fail(`Translation key "${key}" missing in ${lang}`);
    }
  }
  for (const key of Object.keys(dict.ro)) {
    if (!(key in dict.en)) fail(`Translation key "${key}" exists in ro but not in en`);
  }
  for (const key of Object.keys(dict.en)) {
    if (!(key in dict.ro)) fail(`Translation key "${key}" exists in en but not in ro`);
  }
}

// 5. Relative paths only (the site must work under any base path)
for (const f of codeFiles) {
  const src = read(f);
  const bad = src.match(/(?:href|src)\s*=\s*["']\/(?!\/)/g);
  if (bad) fail(`${f}: uses an absolute path (${bad[0]}...). Use relative paths.`);
  if (extname(f) === '.css' && /url\(\s*["']?\/(?!\/)/.test(src)) fail(`${f}: uses an absolute url(/...). Use relative paths.`);
}

// 6. Romanian diacritics use comma-below (ș ț), not the look-alike cedilla letters (ş ţ)
for (const f of [...codeFiles, 'sitemap.xsl', 'data/materials.source.json', 'data/materials.json',
  ...files.filter((x) => x.startsWith('data/results/'))]) {
  if (exists(f) && /[şţŞŢ]/.test(read(f))) fail(`${f}: uses cedilla letters (ş ţ). Use comma-below letters (ș ț).`);
}

// 7. Internal links in static HTML point to files that exist
for (const f of files.filter((x) => extname(x) === '.html')) {
  const src = read(f);
  for (const m of src.matchAll(/(?:href|src)\s*=\s*"([^"]+)"/g)) {
    const url = m[1];
    if (/^(https?:|mailto:|tel:|#|data:)/.test(url) || url.includes('${')) continue;
    const path = url.split(/[?#]/)[0];
    if (path && !existsSync(join(ROOT, dirname(f), path))) fail(`${f}: link to missing file "${url}"`);
  }
}

// 8. SEO head tags and headers (audit Phase 3)
for (const f of files.filter((x) => extname(x) === '.html')) {
  const src = read(f);
  if (!src.includes('<head')) continue;
  if (src.includes('noindex')) {
    if (src.includes('max-image-preview')) fail(`${f}: noindex page must not contain max-image-preview`);
  } else {
    if (!src.includes('max-image-preview:large, max-snippet:-1, max-video-preview:-1')) {
      fail(`${f}: indexable page must contain robots max-image-preview:large, max-snippet:-1, max-video-preview:-1`);
    }
    for (const tag of ['og:image:width', 'og:image:height', 'og:image:alt']) {
      if (!src.includes(tag)) fail(`${f}: indexable page must contain ${tag}`);
    }
  }
}
for (const f of ['index.html', 'en/index.html']) {
  if (exists(f)) {
    const src = read(f);
    if (!src.includes('"EducationalOrganization"')) fail(`${f}: must contain an EducationalOrganization node (audit F5)`);
    if (!src.includes('"logo"')) fail(`${f}: EducationalOrganization must have a logo`);
  }
}
if (exists('_headers')) {
  const h = read('_headers');
  if (!h.includes('/assets/*') || !h.includes('Cache-Control: public, max-age=86400')) {
    fail('_headers: must set "Cache-Control: public, max-age=86400" for /assets/* (audit F4)');
  }
  if (!h.includes('/materiale/pdf/*') || !h.includes('Cache-Control: public, max-age=86400')) {
    fail('_headers: must set "Cache-Control: public, max-age=86400" for /materiale/pdf/* (audit F4)');
  }
  if (!h.includes('https://:version.:project.pages.dev/*')) {
    fail('_headers: must noindex preview deployments with "https://:version.:project.pages.dev/*" (audit F6)');
  }
  if (/^https:\/\/:project\.pages\.dev\/\*$/m.test(h)) {
    fail('_headers: must not noindex "https://:project.pages.dev/*" — that would noindex production');
  }
  if (!h.includes('/sitemap.xsl') || !h.includes('Content-Type: text/xsl')) {
    fail('_headers: must serve /sitemap.xsl as "Content-Type: text/xsl" so browsers apply the sitemap stylesheet');
  }
}
// The sitemap renders as a styled page in browsers (XSLT); crawlers read the raw XML.
if (exists('sitemap.xml')) {
  const sm = read('sitemap.xml');
  if (!sm.includes('<?xml-stylesheet type="text/xsl" href="sitemap.xsl"?>')) {
    fail('sitemap.xml: must reference the stylesheet as <?xml-stylesheet type="text/xsl" href="sitemap.xsl"?>');
  }
}
if (exists('sitemap.xsl')) {
  const xsl = read('sitemap.xsl');
  for (const needle of [
    '<xsl:stylesheet',
    'http://www.w3.org/1999/XSL/Transform',
    'http://www.sitemaps.org/schemas/sitemap/0.9',
    's:urlset/s:url',
    'noindex, follow',
  ]) {
    if (!xsl.includes(needle)) fail(`sitemap.xsl: must contain "${needle}"`);
  }
  const bad = xsl.match(/(?:href|src)\s*=\s*["']\/(?!\/)/g);
  if (bad) fail(`sitemap.xsl: uses an absolute path (${bad[0]}...). Use relative paths.`);
}
// Grade titles carry both numeral forms (audit F2); descriptions are unique (audit F3).
{
  const seen = new Map();
  for (let g = 5; g <= 12; g++) {
    for (const f of [`clasa-${g}.html`, `en/clasa-${g}.html`]) {
      if (!exists(f)) continue;
      const src = read(f);
      const title = (src.match(/<title>([\s\S]*?)<\/title>/) || [, ''])[1];
      if (f === `clasa-${g}.html`) {
        if (!title.includes(`clasa a ${g}-a`) || !title.includes(`a ${Catalog.ROMAN[g]}-a`)) {
          fail(`${f}: title must contain both "clasa a ${g}-a" and "a ${Catalog.ROMAN[g]}-a" (audit F2)`);
        }
      } else if (!title.includes(`Grade ${g}`)) {
        fail(`${f}: title must contain "Grade ${g}"`);
      }
      const desc = (src.match(/<meta name="description" content="([^"]*)"/) || [, null])[1];
      if (desc && !src.includes('noindex')) {
        if (seen.has(desc)) fail(`${f}: description duplicates ${seen.get(desc)} (audit F3)`);
        else seen.set(desc, f);
      }
      // The full intro stays in the server HTML even though the browser
      // collapses it behind a "more" button (SEO: crawlers see everything).
      if (data && data.grades && data.grades[String(g)] && data.grades[String(g)].intro) {
        const lang = f.startsWith('en/') ? 'en' : 'ro';
        const intro = data.grades[String(g)].intro[lang] || data.grades[String(g)].intro.ro;
        if (intro && !src.includes(esc(intro))) fail(`${f}: must contain the full grade intro in the HTML`);
      }
    }
  }
}

// The brand mark borrows the header ink for its letters, but the highlighter
// under them needs its own colour: the page highlighter is nearly invisible on
// the dark theme, so a shared variable would hide half the logo there.
{
  const css = read('assets/css/style.css');
  const markerDefs = (css.match(/--brand-marker\s*:/g) || []).length;
  if (markerDefs < 2) {
    fail(`assets/css/style.css: --brand-marker must be set for the light and the dark theme (found ${markerDefs})`);
  }
  for (const rule of ['.brand-mark', '.brand-text']) {
    if (!css.includes(`${rule} {`)) fail(`assets/css/style.css: missing a rule for ${rule}`);
  }
}

// Dark mode has two doors: the system setting, and the reader's own choice.
// The colours are spelled out twice because CSS cannot share a block across a
// media query, so check that neither copy has drifted from the other.
{
  const css = read('assets/css/style.css');
  const blockOf = (re, what) => {
    const m = css.match(re);
    if (!m) {
      fail(`assets/css/style.css: missing the ${what} dark block`);
      return null;
    }
    return (m[1].match(/--[a-z-]+(?=\s*:)/g) || []).sort().join(',');
  };
  const chosen = blockOf(/:root\[data-theme="dark"\]\s*\{([^}]*)\}/, 'chosen');
  const system = blockOf(/:root:not\(\[data-theme="light"\]\)\s*\{([^}]*)\}/, 'system');
  if (chosen && system && chosen !== system) {
    fail('assets/css/style.css: the two dark blocks set different variables; keep them in sync');
  }
}

if (errors.length) {
  console.error(`FAIL: ${errors.length} problem(s)`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}
console.log(`PASS: ${topics.length} topics, ${materials.length} materials, ${codeFiles.length} files checked`);
